import type { App, Plugin } from 'vue';
import {
  AccordionPlugin,
  //AffixPlugin,
  //AvatarPlugin,
  //AvatarGroupPlugin,
  //BadgePlugin,
  //BreadcrumbsPlugin,
  ButtonPlugin,
  //CollapsePlugin,
  ConfigProviderPlugin,
  ModalPlugin,
  InplacePlugin,
  DrawerPlugin,
  //DropdownPlugin,
  //ImagePlugin,
  //PaginationPlugin,
  //PlaceholderPlugin,
  ScrollbarPlugin,
  SpinnerPlugin,
  //TabsPlugin,
  TagPlugin,
  TextPlugin,
  ContainerPlugin,
  ColPlugin,
  RowPlugin,
  LayoutPlugin,
  FormPlugin,
  FormItemPlugin,
  InputPlugin,
  CheckboxPlugin,
  CheckboxGroupPlugin,
  //DatepickerPlugin,
  //InputRangePlugin,
  InputPasswordPlugin,
  InputNumberPlugin,
  //InputMaskPlugin,
  //InputFilePlugin,
  InputCodePlugin,
  RadioPlugin,
  RadioGroupPlugin,
  SwitchPlugin,
  SelectPlugin,
  AlertPlugin,
  //ProgressPlugin,
  DividerPlugin,
  FlexPlugin,
  InputGroupPlugin,
  MenuPlugin,
  //CountdownPlugin,
  //CalendarPlugin,
} from '../components';
import { ClickOutsidePlugin, LoadingPlugin, TooltipPlugin, VisiblePlugin } from '@vau/core';

export const Vau: Plugin = {
  install (app: App) {
    // Directives
    app.use(ClickOutsidePlugin);
    app.use(LoadingPlugin);
    app.use(TooltipPlugin);
    app.use(VisiblePlugin);

    // Components
    app.use(AccordionPlugin);
    //app.use(AffixPlugin);
    //app.use(AvatarPlugin);
    //app.use(AvatarGroupPlugin);
    //app.use(BadgePlugin);
    //app.use(BreadcrumbsPlugin);
    app.use(ButtonPlugin);
    //app.use(CollapsePlugin);
    app.use(ConfigProviderPlugin);
    app.use(ModalPlugin);
    app.use(InplacePlugin);
    app.use(DrawerPlugin);
    //app.use(DropdownPlugin);
    //app.use(ImagePlugin);
    //app.use(PaginationPlugin);
    //app.use(PlaceholderPlugin);
    app.use(ScrollbarPlugin);
    app.use(SpinnerPlugin);
    //app.use(TabsPlugin);
    app.use(TagPlugin);
    app.use(TextPlugin);
    app.use(ContainerPlugin);
    app.use(ColPlugin);
    app.use(RowPlugin);
    app.use(LayoutPlugin);
    app.use(FormPlugin);
    app.use(FormItemPlugin);
    app.use(InputPlugin);
    app.use(CheckboxPlugin);
    app.use(CheckboxGroupPlugin);
    //app.use(DatepickerPlugin);
    //app.use(InputRangePlugin);
    app.use(InputPasswordPlugin);
    app.use(InputNumberPlugin);
    //app.use(InputMaskPlugin);
    //app.use(InputFilePlugin);
    app.use(InputCodePlugin);
    app.use(RadioPlugin);
    app.use(RadioGroupPlugin);
    app.use(SwitchPlugin);
    app.use(SelectPlugin);
    app.use(AlertPlugin);
    //app.use(ProgressPlugin);
    app.use(DividerPlugin);
    app.use(FlexPlugin);
    app.use(InputGroupPlugin);
    app.use(MenuPlugin);
    //app.use(CountdownPlugin);
    //app.use(CalendarPlugin);
  }
};
